name: x_social
description: "A social media feed app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  loading_animation_widget: ^1.2.0+4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  image_picker: ^1.0.7
  reorderables: ^0.6.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.6.6
  firebase_auth_mocks: ^0.13.0
  fake_cloud_firestore: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg